# FundME
Group 33: CS2102 AY2019/20 Sem 1 Project

=== Introduction
FundME is a crowdfunding application for aspiring creators to publish their project to get funding and for users who are looking to fund a project.

=== Setting Up
1. Install https://www.postgresql.org/download/[PostgreSQL] for your operating system. 
* Remember the username and password that you have set (to be used in step 5 below).
2. Install the https://nodejs.org/en/download/[NodeJS] package for your operating system. 
3. Using your terminal:
* Type `node -v` to check if _NodeJS_ was installed correctly. A Node version number should appear, else reinstall _NodeJS_. 
* Type `npm -v` to check if _npm_ was also installed automatically. An npm version number should appear, else reinstall _NodeJS_.
5. Type `npm install` in your terminal to install various dependencies needed.
6. Use any code editor to edit the _.env_ file to your username and password that you set in step 1. 
* Format: `postgres://username:password@localhost:5432/postgres`
* Default username and password are both `postgres`.
7. Copy and paste all the contents of _schema.sql_ into your Postgres database after you have logged in. Ensure all table creations and insertions were executed correctly without errors.

=== Launching
1. Navigate to the _App_ folder within the project using `cd \App` in your terminal.
2. Type `npm start` in your terminal.
3. Go to the address bar of your internet browser and enter `localhost:3000`. 